import entertainment from "../../Assets/Images/entertainment.jpg";
import entertainment1 from "../../Assets/Images/entertainment1.jpg";
import entertainment2 from "../../Assets/Images/entertainment2.jpg";
import entertainment3 from "../../Assets/Images/entertainment3.jpg";
import entertainment4 from "../../Assets/Images/entertainment4.jpg";
import armchair from "../../Assets/Images/armchair.jpg";
import albanyTable from "../../Assets/Images/albanyTable.jpg";
import emperorBed from "../../Assets/Images/emperorBed.jpg";
import diningTable from "../../Assets/Images/diningTable.jpg";
import modernBookshelf from "../../Assets/Images/modernBookshelf.jpg";
export const productData = {
  productType: [
    { id: "1", type: "all", title: "All" },
    { id: "2", type: "office", title: "Office" },
    { id: "3", type: "livingroom", title: "Living Room" },
    { id: "4", type: "kitchen", title: "Kitchen" },
    { id: "5", type: "bedroom", title: "Bedroom" },
    { id: "6", type: "dining", title: "Dining" },
    { id: "7", type: "kids", title: "Kids" },
  ],
  products: [
    {
      id: "1",
      alt: "Entertainment Center",
      url: entertainment,
      moreurl: [entertainment1, entertainment2, entertainment3, entertainment4],
      title: "Entertainment Center",
      price: "$599.99",
      stocks: "In Stock",
      brand: "Caressa",
      sku: "RecNZ0koOqEmilmoz",
      type: "livingroom",
    },
    {
      id: "2",
      alt: "Suede Armchair",
      url: armchair,
      moreurl: [entertainment1, entertainment2, entertainment3, entertainment4],
      title: "Suede Armchair",
      price: "$159.99",
      stocks: "In Stock",
      brand: "Caressa",
      sku: "RecNZ0koOqEmilmoz",
      type: "office",
    },
    {
      id: "3",
      alt: "Albany Table",
      url: albanyTable,
      moreurl: [entertainment1, entertainment2, entertainment3, entertainment4],
      title: "Albany Table",
      price: "$3,099.99",
      stocks: "In Stock",
      brand: "Caressa",
      sku: "RecNZ0koOqEmilmoz",
      type: "kitchen",
    },
    {
      id: "4",
      alt: "Emperor Bed",
      url: emperorBed,
      moreurl: [entertainment1, entertainment2, entertainment3, entertainment4],
      title: "Emperor Bed",
      price: "$239.99",
      stocks: "In Stock",
      brand: "Caressa",
      sku: "RecNZ0koOqEmilmoz",
      type: "bedroom",
    },
    {
      id: "5",
      alt: "Dining Table",
      url: diningTable,
      moreurl: [entertainment1, entertainment2, entertainment3, entertainment4],
      title: "Dining Table",
      price: "$429.99",
      stocks: "In Stock",
      brand: "Caressa",
      sku: "RecNZ0koOqEmilmoz",
      type: "dining",
    },
    {
      id: "6",
      alt: "Modern Bookshelf",
      url: modernBookshelf,
      moreurl: [entertainment1, entertainment2, entertainment3, entertainment4],
      title: "Modern Bookshelf",
      price: "$319.99",
      stocks: "In Stock",
      brand: "Caressa",
      sku: "RecNZ0koOqEmilmoz",
      type: "kids",
    },
  ],
  featuredProducts: [
    {
      id: "1",
      alt: "product",
      url: entertainment,
      moreurl: [
        "https://v5.airtableusercontent.com/v1/10/10/1668420000000/YvkDsF-yBtZNK8oRV25rVg/NY3p8h_El3zWTt7gGa6O8keb-RVar4iEpOTzkDUeIo5snYrAlMvr4K83C1K2i5qv3FYN3kh_p3Uz8Be9gkrL0g/_rVe_BKndGlwFXtGdEbfaQ-cZ4f1oxSOFXmIVJD_-z4",
        "https://v5.airtableusercontent.com/v1/10/10/1668427200000/BDhl36p1wH2NxLUVZsiNsA/iv2mQJe5R2BPvIHlrGvl32QtEjiTklRk_K5x0iusFp_BvTV_l4TN5edl3Y6OhqFpMgMgm8U3rnmrCCU4fjy6cHRQ-10YzHgamMHWsD3hRAM/X4c3wElebV-wjdXR8soa-bhCWnlxvxuQP9bjEtKNnM4",
        "https://v5.airtableusercontent.com/v1/10/10/1668427200000/W_lxZfrnGQtm1vMyEqLFxg/7tSjiZi8WdgKS91a5IdE2haOIuPmKE-1cws64FBpN7_L2T68wAfg3kXMG_pxhFfk5eQz9ERvpESYP434381YfFdboK5raPSODhqBVmxWikw/sfpkScgodO1Or0HOJPoCwTpqqPq35FtW763tc04xLkE",
        "https://v5.airtableusercontent.com/v1/10/10/1668427200000/PmqGHt4MkLaIt76IEc0nKQ/EvIN8pdLRNvoX6PiHBD11famcovDQM92sWwc4Sm8JIis_ya4tbqvX_XaBhDfQlJ3edGxHMt6QwvvGSTy_etnKP-zdqxEFy19pqQIhQHed5U/LaC8xSfCl7kLGGHJ6ROcz977fQeU457QzAygaZUEt6A",
        "https://v5.airtableusercontent.com/v1/10/10/1668427200000/eu7_AnvTTxvAn-TpuR6cKg/iGqmG674iIssOYhOW_-b-sZnVGpgNozCEiewS3pnYr1e9k82-cNPQsX7CCrZgE6EoEIjIoNCV7VJr_iZ7GlntSfhor8yAl_OTkO3o-e0E60/1Zx5hO8ehmvvxTgqrFa6lpTPUav1iNoYPSfMPckzZ8Y",
      ],
      title: "Entertainment Center",
      price: "$599.99",
      stocks: "In Stock",
      brand: "Caressa",
      sku: "RecNZ0koOqEmilmoz",
    },
    {
      id: "4",
      alt: "Emperor Bed",
      url: emperorBed,
      moreurl: [entertainment1, entertainment2, entertainment3, entertainment4],
      title: "Emperor Bed",
      price: "$239.99",
      stocks: "In Stock",
      brand: "Caressa",
      sku: "RecNZ0koOqEmilmoz",
      type: "bedroom",
    },
    {
      id: "6",
      alt: "Modern Bookshelf",
      url: modernBookshelf,
      moreurl: [entertainment1, entertainment2, entertainment3, entertainment4],
      title: "Modern Bookshelf",
      price: "$319.99",
      stocks: "In Stock",
      brand: "Caressa",
      sku: "RecNZ0koOqEmilmoz",
      type: "kids",
    },
  ],
  selectedProducts: [],
  searchProducts: [],
};
